// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB6dLIrsMbyM53aN2-55CL75xpHMYP1E0',
    appId: '1:135837002281:web:aa174210996f052f508a38',
    messagingSenderId: '135837002281',
    projectId: 'notesai-5c9cc',
    authDomain: 'notesai-5c9cc.firebaseapp.com',
    storageBucket: 'notesai-5c9cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHhadjepU0lMX6NokW3S_UmcmbZx5M4c',
    appId: '1:135837002281:android:0dc423156865402a508a38',
    messagingSenderId: '135837002281',
    projectId: 'notesai-5c9cc',
    storageBucket: 'notesai-5c9cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE3lY-zO1IZi47WX1qQQxHxRLSh4ERaxo',
    appId: '1:135837002281:ios:3ad2a00aae4a1313508a38',
    messagingSenderId: '135837002281',
    projectId: 'notesai-5c9cc',
    storageBucket: 'notesai-5c9cc.firebasestorage.app',
    iosClientId: '135837002281-3kt3b0qgpgk8jbet2bk1hrhh11n7vle3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE3lY-zO1IZi47WX1qQQxHxRLSh4ERaxo',
    appId: '1:135837002281:ios:3ad2a00aae4a1313508a38',
    messagingSenderId: '135837002281',
    projectId: 'notesai-5c9cc',
    storageBucket: 'notesai-5c9cc.firebasestorage.app',
    iosClientId: '135837002281-3kt3b0qgpgk8jbet2bk1hrhh11n7vle3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB6dLIrsMbyM53aN2-55CL75xpHMYP1E0',
    appId: '1:135837002281:web:436ae4cdc15fd0cb508a38',
    messagingSenderId: '135837002281',
    projectId: 'notesai-5c9cc',
    authDomain: 'notesai-5c9cc.firebaseapp.com',
    storageBucket: 'notesai-5c9cc.firebasestorage.app',
  );
}
